import type { Permission } from '@workforce/domain';
import type { RouteDefinition } from './routes';

/**
 * ทะเบียน route ที่ครอบคลุมทั้ง API surface
 *
 * สร้างจาก controller จริงเพื่อให้ OpenAPI ไม่ตกหล่น endpoint ใด —
 * `authorization.test.ts` ตรวจว่าทะเบียนนี้กับสิ่งที่ Nest ลงทะเบียนไว้ตรงกันเสมอ
 *
 * รายการที่มี request/response schema ละเอียดอยู่ใน `routes.ts` และจะ override
 * รายการที่นี่เมื่อ operationId ตรงกัน
 */
export const OPERATIONAL_ROUTES: readonly Omit<RouteDefinition, 'response'>[] = [
  {
    operationId: 'requestAdjustment_post',
    method: 'post',
    path: '/attendance-correction-requests',
    summary: 'POST /attendance-correction-requests',
    tag: 'attendance',
    permissions: ['workforce.attendance.correct.request'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'approveAdjustment_post',
    method: 'post',
    path: '/attendance-correction-requests/{adjustmentId}/approve',
    summary: 'POST /attendance-correction-requests/{adjustmentId}/approve',
    tag: 'attendance',
    permissions: ['workforce.attendance.correct.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'listExceptions_get',
    method: 'get',
    path: '/attendance-exceptions',
    summary: 'GET /attendance-exceptions',
    tag: 'attendance',
    permissions: ['workforce.attendance.read.all'] as Permission[],
  },
  {
    operationId: 'resolveException_post',
    method: 'post',
    path: '/attendance-exceptions/{exceptionId}/resolve',
    summary: 'POST /attendance-exceptions/{exceptionId}/resolve',
    tag: 'attendance',
    permissions: ['workforce.attendance.correct.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'listResults_get',
    method: 'get',
    path: '/attendance-results',
    summary: 'GET /attendance-results',
    tag: 'attendance',
    permissions: ['workforce.attendance.read.all'] as Permission[],
  },
  {
    operationId: 'recalculate_post',
    method: 'post',
    path: '/attendance-results:recalculate',
    summary: 'POST /attendance-results:recalculate',
    tag: 'attendance',
    permissions: ['workforce.attendance.read.all'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'listCalendars_get',
    method: 'get',
    path: '/holiday-calendars',
    summary: 'GET /holiday-calendars',
    tag: 'attendance',
    permissions: ['workforce.scheduling.read'] as Permission[],
    idempotent: false,
    successStatus: 200,
  },
  {
    operationId: 'deleteHolidayDate_post',
    method: 'post',
    path: '/holiday-dates/{holidayDateId}/delete',
    summary: 'POST /holiday-dates/{holidayDateId}/delete',
    tag: 'attendance',
    permissions: ['workforce.scheduling.manage'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'createCalendar_post',
    method: 'post',
    path: '/holiday-calendars',
    summary: 'POST /holiday-calendars',
    tag: 'attendance',
    permissions: ['workforce.scheduling.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'addHolidays_post',
    method: 'post',
    path: '/holiday-calendars/{calendarId}/dates',
    summary: 'POST /holiday-calendars/{calendarId}/dates',
    tag: 'attendance',
    permissions: ['workforce.scheduling.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'setPattern_post',
    method: 'post',
    path: '/recurring-work-patterns',
    summary: 'POST /recurring-work-patterns',
    tag: 'attendance',
    permissions: ['workforce.scheduling.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'createRoster_post',
    method: 'post',
    path: '/roster-periods',
    summary: 'POST /roster-periods',
    tag: 'attendance',
    permissions: ['workforce.scheduling.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'publishRoster_post',
    method: 'post',
    path: '/roster-periods/{rosterId}/publish',
    summary: 'POST /roster-periods/{rosterId}/publish',
    tag: 'attendance',
    permissions: ['workforce.scheduling.publish'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'bulkUpsert_post',
    method: 'post',
    path: '/roster-periods/{rosterId}/shift-assignments:bulk-upsert',
    summary: 'POST /roster-periods/{rosterId}/shift-assignments:bulk-upsert',
    tag: 'attendance',
    permissions: ['workforce.scheduling.manage'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'createShift_post',
    method: 'post',
    path: '/shifts',
    summary: 'POST /shifts',
    tag: 'attendance',
    permissions: ['workforce.scheduling.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'createWorkPolicy_post',
    method: 'post',
    path: '/work-policies',
    summary: 'POST /work-policies',
    tag: 'attendance',
    permissions: ['workforce.scheduling.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'list_get',
    method: 'get',
    path: '/audit-events',
    summary: 'GET /audit-events',
    tag: 'audit',
    permissions: ['workforce.audit.read'] as Permission[],
  },
  {
    operationId: 'downloadUrl_get',
    method: 'get',
    path: '/attendance-evidence/{evidenceId}/download-url',
    summary: 'GET /attendance-evidence/{evidenceId}/download-url',
    tag: 'checkin',
    permissions: ['workforce.attendance.evidence.read'] as Permission[],
  },
  {
    operationId: 'createPolicyGroup_post',
    method: 'post',
    path: '/attendance-policy-groups',
    summary: 'POST /attendance-policy-groups',
    tag: 'checkin',
    permissions: ['workforce.settings.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'assignPolicyGroup_post',
    method: 'post',
    path: '/attendance-policy-groups/{groupId}/members',
    summary: 'POST /attendance-policy-groups/{groupId}/members',
    tag: 'checkin',
    permissions: ['workforce.settings.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'listRiskAssessments_get',
    method: 'get',
    path: '/attendance-risk-assessments',
    summary: 'GET /attendance-risk-assessments',
    tag: 'checkin',
    permissions: ['workforce.attendance.evidence.read'] as Permission[],
  },
  {
    operationId: 'review_post',
    method: 'post',
    path: '/attendance-risk-assessments/{assessmentId}/review',
    summary: 'POST /attendance-risk-assessments/{assessmentId}/review',
    tag: 'checkin',
    permissions: ['workforce.attendance.correct.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'listMyDevices_get',
    method: 'get',
    path: '/me/mobile-devices',
    summary: 'GET /me/mobile-devices',
    tag: 'checkin',
    permissions: ['workforce.attendance.read.self'] as Permission[],
  },
  {
    operationId: 'enrollDevice_post',
    method: 'post',
    path: '/mobile-devices/enroll',
    summary: 'POST /mobile-devices/enroll',
    tag: 'checkin',
    permissions: ['workforce.attendance.read.self'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'approveDevice_post',
    method: 'post',
    path: '/mobile-devices/{registrationId}/approve',
    summary: 'POST /mobile-devices/{registrationId}/approve',
    tag: 'checkin',
    permissions: ['workforce.people.manage'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'createSession_post',
    method: 'post',
    path: '/time-events/photo-checkin-sessions',
    summary: 'POST /time-events/photo-checkin-sessions',
    tag: 'checkin',
    permissions: ['workforce.attendance.read.self'] as Permission[],
    successStatus: 201,
  },
  {
    operationId: 'commitSession_post',
    method: 'post',
    path: '/time-events/photo-checkin-sessions/{sessionId}/commit',
    summary: 'POST /time-events/photo-checkin-sessions/{sessionId}/commit',
    tag: 'checkin',
    permissions: ['workforce.attendance.read.self'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'attachEvidence_post',
    method: 'post',
    path: '/time-events/photo-checkin-sessions/{sessionId}/evidence',
    summary: 'POST /time-events/photo-checkin-sessions/{sessionId}/evidence',
    tag: 'checkin',
    permissions: ['workforce.attendance.read.self'] as Permission[],
    successStatus: 201,
  },
  {
    operationId: 'list_get',
    method: 'get',
    path: '/compensation-rates',
    summary: 'GET /compensation-rates',
    tag: 'compensation',
    permissions: ['workforce.payroll.read'] as Permission[],
  },
  {
    operationId: 'create_post',
    method: 'post',
    path: '/compensation-rates',
    summary: 'POST /compensation-rates',
    tag: 'compensation',
    permissions: ['workforce.payroll.prepare'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'listEnrollments_get',
    method: 'get',
    path: '/biometric-enrollments',
    summary: 'GET /biometric-enrollments',
    tag: 'devices',
    permissions: ['workforce.devices.read'] as Permission[],
  },
  {
    operationId: 'requestEnrollment_post',
    method: 'post',
    path: '/biometric-enrollments',
    summary: 'POST /biometric-enrollments',
    tag: 'devices',
    permissions: ['workforce.devices.enroll-biometric'] as Permission[],
    idempotent: true,
    successStatus: 202,
  },
  {
    operationId: 'list_get',
    method: 'get',
    path: '/devices',
    summary: 'GET /devices',
    tag: 'devices',
    permissions: ['workforce.devices.read'] as Permission[],
  },
  {
    operationId: 'create_post',
    method: 'post',
    path: '/devices',
    summary: 'POST /devices',
    tag: 'devices',
    permissions: ['workforce.devices.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'get_get',
    method: 'get',
    path: '/devices/{deviceId}',
    summary: 'GET /devices/{deviceId}',
    tag: 'devices',
    permissions: ['workforce.devices.read'] as Permission[],
  },
  {
    operationId: 'issueActivationToken_post',
    method: 'post',
    path: '/devices/{deviceId}/activation-tokens',
    summary: 'POST /devices/{deviceId}/activation-tokens',
    tag: 'devices',
    permissions: ['workforce.devices.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'revoke_post',
    method: 'post',
    path: '/devices/{deviceId}/revoke',
    summary: 'POST /devices/{deviceId}/revoke',
    tag: 'devices',
    permissions: ['workforce.devices.revoke'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'createBankBatch_post',
    method: 'post',
    path: '/bank-batches',
    summary: 'POST /bank-batches',
    tag: 'documents',
    permissions: ['workforce.payroll.export'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'verifyBankBatch_get',
    method: 'get',
    path: '/bank-batches/{batchId}/verify',
    summary: 'GET /bank-batches/{batchId}/verify',
    tag: 'documents',
    permissions: ['workforce.payroll.export'] as Permission[],
  },
  {
    operationId: 'createBankProfile_post',
    method: 'post',
    path: '/bank-profiles',
    summary: 'POST /bank-profiles',
    tag: 'documents',
    permissions: ['workforce.payroll.export'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'myPayslips_get',
    method: 'get',
    path: '/me/payslips',
    summary: 'GET /me/payslips',
    tag: 'documents',
    permissions: ['workforce.payslip.read.self'] as Permission[],
  },
  {
    operationId: 'exportRegister_post',
    method: 'post',
    path: '/payroll-runs/{runId}/export-jobs',
    summary: 'POST /payroll-runs/{runId}/export-jobs',
    tag: 'documents',
    permissions: ['workforce.payroll.export'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'markPaid_post',
    method: 'post',
    path: '/payroll-runs/{runId}/mark-paid',
    summary: 'POST /payroll-runs/{runId}/mark-paid',
    tag: 'documents',
    permissions: ['workforce.payroll.mark-paid'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'publishPayslips_post',
    method: 'post',
    path: '/payroll-runs/{runId}/payslips:publish',
    summary: 'POST /payroll-runs/{runId}/payslips:publish',
    tag: 'documents',
    permissions: ['workforce.payroll.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'downloadPayslip_get',
    method: 'get',
    path: '/payslips/{payslipId}/download-url',
    summary: 'GET /payslips/{payslipId}/download-url',
    tag: 'documents',
    permissions: ['workforce.payslip.read.self'] as Permission[],
  },
  {
    operationId: 'activate_post',
    method: 'post',
    path: '/device-activation',
    summary: 'POST /device-activation',
    tag: 'device-ingestion',
    permissions: null,
    publicReason: 'เครื่องยังไม่มี credential ที่จะใช้เซ็น; ความปลอดภัยมาจาก token ใช้ครั้งเดียวที่มีวันหมดอายุ',
    successStatus: 200,
  },
  {
    operationId: 'commands_get',
    method: 'get',
    path: '/device-ingestion/commands',
    summary: 'GET /device-ingestion/commands',
    tag: 'device-ingestion',
    permissions: null,
    deviceAuth: true,
  },
  {
    operationId: 'heartbeat_post',
    method: 'post',
    path: '/device-ingestion/heartbeats',
    summary: 'POST /device-ingestion/heartbeats',
    tag: 'device-ingestion',
    permissions: null,
    deviceAuth: true,
    successStatus: 201,
  },
  {
    operationId: 'syncState_get',
    method: 'get',
    path: '/device-ingestion/sync-state',
    summary: 'GET /device-ingestion/sync-state',
    tag: 'device-ingestion',
    permissions: null,
    deviceAuth: true,
  },
  {
    operationId: 'legacyAttendance_post',
    method: 'post',
    path: '/legacy/attendance',
    summary: 'POST /legacy/attendance',
    tag: 'device-ingestion',
    permissions: null,
    publicReason: 'firmware เดิมเซ็นไม่ได้; ป้องกันด้วย LEGACY_INGEST_KEY และปิดสนิทเมื่อไม่ตั้งค่า',
    successStatus: 200,
  },
  {
    operationId: 'listCompanies_get',
    method: 'get',
    path: '/companies',
    summary: 'GET /companies',
    tag: 'organization',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'createCompany_post',
    method: 'post',
    path: '/companies',
    summary: 'POST /companies',
    tag: 'organization',
    permissions: ['workforce.settings.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'getCompany_get',
    method: 'get',
    path: '/companies/{companyId}',
    summary: 'GET /companies/{companyId}',
    tag: 'organization',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'updateCompany_patch',
    method: 'patch',
    path: '/companies/{companyId}',
    summary: 'PATCH /companies/{companyId}',
    tag: 'organization',
    permissions: ['workforce.settings.manage'] as Permission[],
  },
  {
    operationId: 'listOrgUnits_get',
    method: 'get',
    path: '/org-units',
    summary: 'GET /org-units',
    tag: 'organization',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'createOrgUnit_post',
    method: 'post',
    path: '/org-units',
    summary: 'POST /org-units',
    tag: 'organization',
    permissions: ['workforce.settings.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'listPositions_get',
    method: 'get',
    path: '/positions',
    summary: 'GET /positions',
    tag: 'organization',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'createPosition_post',
    method: 'post',
    path: '/positions',
    summary: 'POST /positions',
    tag: 'organization',
    permissions: ['workforce.settings.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'listSites_get',
    method: 'get',
    path: '/sites',
    summary: 'GET /sites',
    tag: 'organization',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'createSite_post',
    method: 'post',
    path: '/sites',
    summary: 'POST /sites',
    tag: 'organization',
    permissions: ['workforce.settings.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'createPayItem_post',
    method: 'post',
    path: '/pay-items',
    summary: 'POST /pay-items',
    tag: 'payroll',
    permissions: ['workforce.payroll.prepare'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'publishPayItem_post',
    method: 'post',
    path: '/pay-items/{payItemId}/publish',
    summary: 'POST /pay-items/{payItemId}/publish',
    tag: 'payroll',
    permissions: ['workforce.payroll.prepare'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'createPeriod_post',
    method: 'post',
    path: '/payroll-periods',
    summary: 'POST /payroll-periods',
    tag: 'payroll',
    permissions: ['workforce.payroll.prepare'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'createRun_post',
    method: 'post',
    path: '/payroll-runs',
    summary: 'POST /payroll-runs',
    tag: 'payroll',
    permissions: ['workforce.payroll.prepare'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'approve_post',
    method: 'post',
    path: '/payroll-runs/{runId}/approve',
    summary: 'POST /payroll-runs/{runId}/approve',
    tag: 'payroll',
    permissions: ['workforce.payroll.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'calculate_post',
    method: 'post',
    path: '/payroll-runs/{runId}/calculate',
    summary: 'POST /payroll-runs/{runId}/calculate',
    tag: 'payroll',
    permissions: ['workforce.payroll.calculate'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'listResults_get',
    method: 'get',
    path: '/payroll-runs/{runId}/employees',
    summary: 'GET /payroll-runs/{runId}/employees',
    tag: 'payroll',
    permissions: ['workforce.payroll.read'] as Permission[],
  },
  {
    operationId: 'trace_get',
    method: 'get',
    path: '/payroll-runs/{runId}/employees/{employmentId}/trace',
    summary: 'GET /payroll-runs/{runId}/employees/{employmentId}/trace',
    tag: 'payroll',
    permissions: ['workforce.payroll.read'] as Permission[],
  },
  {
    operationId: 'lock_post',
    method: 'post',
    path: '/payroll-runs/{runId}/lock',
    summary: 'POST /payroll-runs/{runId}/lock',
    tag: 'payroll',
    permissions: ['workforce.payroll.lock'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'reject_post',
    method: 'post',
    path: '/payroll-runs/{runId}/reject',
    summary: 'POST /payroll-runs/{runId}/reject',
    tag: 'payroll',
    permissions: ['workforce.payroll.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'snapshot_post',
    method: 'post',
    path: '/payroll-runs/{runId}/snapshot',
    summary: 'POST /payroll-runs/{runId}/snapshot',
    tag: 'payroll',
    permissions: ['workforce.payroll.prepare'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'listLeaveTypes_get',
    method: 'get',
    path: '/leave-types',
    summary: 'GET /leave-types',
    tag: 'workflow',
    // ทุกคนต้องอ่านได้เพื่อเลือกประเภทตอนขอลา ไม่มีอะไรเป็นความลับ
    permissions: [] as Permission[],
  },
  {
    operationId: 'leaveCalendar_get',
    method: 'get',
    path: '/leave-calendar',
    summary: 'GET /leave-calendar',
    tag: 'workflow',
    // เปล่า = ขอแค่ยืนยันตัวตนแล้ว ทั้งทีมต้องเห็นว่าใครหยุดวันไหน
    // (เหตุผลกับประเภทการลาไม่ถูกส่งออกมา)
    permissions: [] as Permission[],
  },
  {
    operationId: 'leaveRequests_get',
    method: 'get',
    path: '/leave-requests',
    summary: 'GET /leave-requests',
    tag: 'workflow',
    permissions: ['workforce.leave.manage'] as Permission[],
  },
  {
    operationId: 'submit_post',
    method: 'post',
    path: '/payroll-runs/{runId}/submit',
    summary: 'POST /payroll-runs/{runId}/submit',
    tag: 'payroll',
    permissions: ['workforce.payroll.prepare'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'createRuleSet_post',
    method: 'post',
    path: '/statutory-rule-sets',
    summary: 'POST /statutory-rule-sets',
    tag: 'payroll',
    permissions: ['workforce.payroll.prepare'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'publishRuleSet_post',
    method: 'post',
    path: '/statutory-rule-sets/{ruleSetId}/publish',
    summary: 'POST /statutory-rule-sets/{ruleSetId}/publish',
    tag: 'payroll',
    permissions: ['workforce.payroll.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'listEmployments_get',
    method: 'get',
    path: '/employments',
    summary: 'GET /employments',
    tag: 'people',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'createEmployment_post',
    method: 'post',
    path: '/employments',
    summary: 'POST /employments',
    tag: 'people',
    permissions: ['workforce.people.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'getEmployment_get',
    method: 'get',
    path: '/employments/{employmentId}',
    summary: 'GET /employments/{employmentId}',
    tag: 'people',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'listAssignments_get',
    method: 'get',
    path: '/employments/{employmentId}/assignments',
    summary: 'GET /employments/{employmentId}/assignments',
    tag: 'people',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'createAssignment_post',
    method: 'post',
    path: '/employments/{employmentId}/assignments',
    summary: 'POST /employments/{employmentId}/assignments',
    tag: 'people',
    permissions: ['workforce.people.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'terminateEmployment_post',
    method: 'post',
    path: '/employments/{employmentId}/terminate',
    summary: 'POST /employments/{employmentId}/terminate',
    tag: 'people',
    permissions: ['workforce.people.manage'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'listPeople_get',
    method: 'get',
    path: '/people',
    summary: 'GET /people',
    tag: 'people',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'createPerson_post',
    method: 'post',
    path: '/people',
    summary: 'POST /people',
    tag: 'people',
    permissions: ['workforce.people.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'getPerson_get',
    method: 'get',
    path: '/people/{personId}',
    summary: 'GET /people/{personId}',
    tag: 'people',
    permissions: ['workforce.people.read'] as Permission[],
  },
  {
    operationId: 'updatePerson_patch',
    method: 'patch',
    path: '/people/{personId}',
    summary: 'PATCH /people/{personId}',
    tag: 'people',
    permissions: ['workforce.people.manage'] as Permission[],
  },
  {
    operationId: 'health_get',
    method: 'get',
    path: '/health',
    summary: 'GET /health',
    tag: 'system',
    permissions: null,
    publicReason: 'load balancer liveness probe',
  },
  {
    operationId: 'ready_get',
    method: 'get',
    path: '/health/ready',
    summary: 'GET /health/ready',
    tag: 'system',
    permissions: null,
    publicReason: 'load balancer readiness probe',
  },
  {
    operationId: 'me_get',
    method: 'get',
    path: '/me',
    summary: 'GET /me',
    tag: 'system',
    permissions: [] as Permission[],
  },
  {
    operationId: 'balance_get',
    method: 'get',
    path: '/leave-balances',
    summary: 'GET /leave-balances',
    tag: 'workflow',
    permissions: ['workforce.leave.manage'] as Permission[],
  },
  {
    operationId: 'grant_post',
    method: 'post',
    path: '/leave-balances:grant',
    summary: 'POST /leave-balances:grant',
    tag: 'workflow',
    permissions: ['workforce.leave.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'submit_post',
    method: 'post',
    path: '/leave-requests',
    summary: 'POST /leave-requests',
    tag: 'workflow',
    permissions: ['workforce.leave.request'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'cancel_post',
    method: 'post',
    path: '/leave-requests/{requestId}/cancel',
    summary: 'POST /leave-requests/{requestId}/cancel',
    tag: 'workflow',
    permissions: ['workforce.leave.request'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'decide_post',
    method: 'post',
    path: '/leave-requests/{requestId}/decide',
    summary: 'POST /leave-requests/{requestId}/decide',
    tag: 'workflow',
    permissions: ['workforce.leave.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'createType_post',
    method: 'post',
    path: '/leave-types',
    summary: 'POST /leave-types',
    tag: 'workflow',
    permissions: ['workforce.leave.manage'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'list_get',
    method: 'get',
    path: '/overtime-requests',
    summary: 'GET /overtime-requests',
    tag: 'workflow',
    permissions: ['workforce.overtime.manage'] as Permission[],
  },
  {
    operationId: 'submit_post',
    method: 'post',
    path: '/overtime-requests',
    summary: 'POST /overtime-requests',
    tag: 'workflow',
    permissions: ['workforce.overtime.request'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'finalApprove_post',
    method: 'post',
    path: '/overtime-requests/{requestId}/final-approve',
    summary: 'POST /overtime-requests/{requestId}/final-approve',
    tag: 'workflow',
    permissions: ['workforce.overtime.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'preApprove_post',
    method: 'post',
    path: '/overtime-requests/{requestId}/pre-approve',
    summary: 'POST /overtime-requests/{requestId}/pre-approve',
    tag: 'workflow',
    permissions: ['workforce.overtime.approve'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'createPeriod_post',
    method: 'post',
    path: '/timesheet-periods',
    summary: 'POST /timesheet-periods',
    tag: 'workflow',
    permissions: ['workforce.timesheet.review'] as Permission[],
    idempotent: true,
    successStatus: 201,
  },
  {
    operationId: 'close_post',
    method: 'post',
    path: '/timesheet-periods/{periodId}/close',
    summary: 'POST /timesheet-periods/{periodId}/close',
    tag: 'workflow',
    permissions: ['workforce.timesheet.close'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'generate_post',
    method: 'post',
    path: '/timesheet-periods/{periodId}/generate',
    summary: 'POST /timesheet-periods/{periodId}/generate',
    tag: 'workflow',
    permissions: ['workforce.timesheet.review'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'reopen_post',
    method: 'post',
    path: '/timesheet-periods/{periodId}/reopen',
    summary: 'POST /timesheet-periods/{periodId}/reopen',
    tag: 'workflow',
    permissions: ['workforce.timesheet.reopen'] as Permission[],
    idempotent: true,
    successStatus: 200,
  },
  {
    operationId: 'list_get',
    method: 'get',
    path: '/timesheet-periods/{periodId}/timesheets',
    summary: 'GET /timesheet-periods/{periodId}/timesheets',
    tag: 'workflow',
    permissions: ['workforce.timesheet.review'] as Permission[],
  },
  {
    operationId: 'listPayrollRuns_get',
    method: 'get',
    path: '/payroll-runs',
    summary: 'GET /payroll-runs',
    tag: 'payroll',
    permissions: ['workforce.payroll.read'] as Permission[],
  },
  {
    operationId: 'getPayrollRun_get',
    method: 'get',
    path: '/payroll-runs/{runId}',
    summary: 'GET /payroll-runs/{runId}',
    tag: 'payroll',
    permissions: ['workforce.payroll.read'] as Permission[],
  },
  {
    operationId: 'listPayrollPeriods_get',
    method: 'get',
    path: '/payroll-periods',
    summary: 'GET /payroll-periods',
    tag: 'payroll',
    permissions: ['workforce.payroll.read'] as Permission[],
  },
  {
    operationId: 'listRuleSets_get',
    method: 'get',
    path: '/statutory-rule-sets',
    summary: 'GET /statutory-rule-sets',
    tag: 'payroll',
    permissions: ['workforce.payroll.read'] as Permission[],
  },
  {
    operationId: 'listPayItems_get',
    method: 'get',
    path: '/pay-items',
    summary: 'GET /pay-items',
    tag: 'payroll',
    permissions: ['workforce.payroll.read'] as Permission[],
  },
  {
    operationId: 'listTimesheetPeriods_get',
    method: 'get',
    path: '/timesheet-periods',
    summary: 'GET /timesheet-periods',
    tag: 'timesheets',
    permissions: ['workforce.timesheet.review'] as Permission[],
  },
  {
    operationId: 'listShifts_get',
    method: 'get',
    path: '/shifts',
    summary: 'GET /shifts',
    tag: 'scheduling',
    permissions: ['workforce.scheduling.read'] as Permission[],
  },
  {
    operationId: 'listWorkPolicies_get',
    method: 'get',
    path: '/work-policies',
    summary: 'GET /work-policies',
    tag: 'scheduling',
    permissions: ['workforce.scheduling.read'] as Permission[],
  },
  {
    operationId: 'listRosterPeriods_get',
    method: 'get',
    path: '/roster-periods',
    summary: 'GET /roster-periods',
    tag: 'scheduling',
    permissions: ['workforce.scheduling.read'] as Permission[],
  },
  {
    operationId: 'listShiftAssignments_get',
    method: 'get',
    path: '/shift-assignments',
    summary: 'GET /shift-assignments',
    tag: 'scheduling',
    permissions: ['workforce.scheduling.read'] as Permission[],
  },
  {
    operationId: 'attendanceSummary_get',
    method: 'get',
    path: '/attendance-summary',
    summary: 'GET /attendance-summary',
    tag: 'attendance',
    permissions: ['workforce.attendance.read.all'] as Permission[],
  },
];
