import type { Permission } from '@workforce/domain';
import type { z } from 'zod';
import { listAuditEventsQuerySchema, auditEventSchema } from './audit';
import { API_BASE_PATH, pageSchema } from './common';
import {
  ackCommandSchema,
  activationTokenSchema,
  biometricEnrollmentSchema,
  createDeviceSchema,
  deleteEnrollmentSchema,
  deviceActivationRequestSchema,
  deviceActivationResponseSchema,
  deviceCommandSchema,
  deviceSchema,
  issueActivationTokenSchema,
  listDevicesQuerySchema,
  requestEnrollmentSchema,
  revokeDeviceSchema,
} from './devices';
import {
  deviceBatchSchema,
  heartbeatSchema,
  ingestResultSchema,
  legacyAttendanceSchema,
  syncStateSchema,
} from './ingestion';
import { healthSchema, meSchema, readinessSchema } from './identity';
import {
  companySchema,
  createCompanySchema,
  createOrgUnitSchema,
  createPositionSchema,
  createSiteSchema,
  listCompaniesQuerySchema,
  listOrgUnitsQuerySchema,
  listPositionsQuerySchema,
  listSitesQuerySchema,
  orgUnitSchema,
  positionSchema,
  siteSchema,
  updateCompanySchema,
} from './organization';
import {
  assignmentSchema,
  compensationSchema,
  createAssignmentSchema,
  createCompensationSchema,
  createEmploymentSchema,
  createPersonSchema,
  employmentSchema,
  listCompensationQuerySchema,
  listEmploymentsQuerySchema,
  listPeopleQuerySchema,
  personSchema,
  terminateEmploymentSchema,
  updatePersonSchema,
} from './people';

export interface RouteDefinition {
  operationId: string;
  method: 'get' | 'post' | 'patch' | 'delete';
  /** path ไม่รวม base path เช่น `/companies/{id}` */
  path: string;
  summary: string;
  tag: string;
  /** null = ไม่ต้องมี principal — ต้องระบุ `deviceAuth` หรือ `publicReason` กำกับเสมอ */
  permissions: readonly Permission[] | null;
  /** authenticate ด้วยลายเซ็นของเครื่องแทน JWT ของผู้ใช้ (spec §6.2) */
  deviceAuth?: boolean;
  /** เหตุผลที่เปิดสาธารณะได้จริง — บังคับให้เขียนออกมา ไม่ใช่ลืมประกาศสิทธิ์ */
  publicReason?: string;
  /** true = ต้องส่ง Idempotency-Key (ADR-0008) */
  idempotent?: boolean;
  query?: z.ZodTypeAny;
  body?: z.ZodTypeAny;
  response: z.ZodTypeAny;
  successStatus?: number;
}

/**
 * Route registry — แหล่งความจริงเดียวของ API surface ใน Phase 1
 *
 * ใช้ 3 ทาง:
 *   1. generate OpenAPI (`emit-openapi`)
 *   2. `permission-coverage.test.ts` ตรวจว่าไม่มี route ที่ลืมประกาศสิทธิ์
 *   3. `authorization.test.ts` วนสร้าง negative test อัตโนมัติจากรายการนี้
 */
export const ROUTES: readonly RouteDefinition[] = [
  {
    operationId: 'getHealth',
    method: 'get',
    path: '/health',
    summary: 'Liveness probe',
    tag: 'system',
    permissions: null,
    publicReason: 'load balancer liveness probe',
    response: healthSchema,
  },
  {
    operationId: 'getReadiness',
    method: 'get',
    path: '/health/ready',
    summary: 'Readiness probe (database + schema version)',
    tag: 'system',
    permissions: null,
    publicReason: 'load balancer readiness probe',
    response: readinessSchema,
  },
  {
    operationId: 'getMe',
    method: 'get',
    path: '/me',
    summary: 'ข้อมูลตัวตนและสิทธิ์ของผู้เรียก',
    tag: 'identity',
    permissions: [],
    response: meSchema,
  },

  // --- organization ---
  {
    operationId: 'listCompanies',
    method: 'get',
    path: '/companies',
    summary: 'รายการบริษัทใน tenant',
    tag: 'organization',
    permissions: ['workforce.people.read'],
    query: listCompaniesQuerySchema,
    response: pageSchema(companySchema),
  },
  {
    operationId: 'createCompany',
    method: 'post',
    path: '/companies',
    summary: 'สร้างบริษัท',
    tag: 'organization',
    permissions: ['workforce.settings.manage'],
    idempotent: true,
    body: createCompanySchema,
    response: companySchema,
    successStatus: 201,
  },
  {
    operationId: 'getCompany',
    method: 'get',
    path: '/companies/{companyId}',
    summary: 'ดูบริษัท',
    tag: 'organization',
    permissions: ['workforce.people.read'],
    response: companySchema,
  },
  {
    operationId: 'updateCompany',
    method: 'patch',
    path: '/companies/{companyId}',
    summary: 'แก้ไขบริษัท',
    tag: 'organization',
    permissions: ['workforce.settings.manage'],
    body: updateCompanySchema,
    response: companySchema,
  },
  {
    operationId: 'listOrgUnits',
    method: 'get',
    path: '/org-units',
    summary: 'รายการหน่วยงาน',
    tag: 'organization',
    permissions: ['workforce.people.read'],
    query: listOrgUnitsQuerySchema,
    response: pageSchema(orgUnitSchema),
  },
  {
    operationId: 'createOrgUnit',
    method: 'post',
    path: '/org-units',
    summary: 'สร้างหน่วยงาน',
    tag: 'organization',
    permissions: ['workforce.settings.manage'],
    idempotent: true,
    body: createOrgUnitSchema,
    response: orgUnitSchema,
    successStatus: 201,
  },
  {
    operationId: 'listSites',
    method: 'get',
    path: '/sites',
    summary: 'รายการสถานที่ทำงาน',
    tag: 'organization',
    permissions: ['workforce.people.read'],
    query: listSitesQuerySchema,
    response: pageSchema(siteSchema),
  },
  {
    operationId: 'createSite',
    method: 'post',
    path: '/sites',
    summary: 'สร้างสถานที่ทำงาน',
    tag: 'organization',
    permissions: ['workforce.settings.manage'],
    idempotent: true,
    body: createSiteSchema,
    response: siteSchema,
    successStatus: 201,
  },
  {
    operationId: 'listPositions',
    method: 'get',
    path: '/positions',
    summary: 'รายการตำแหน่ง',
    tag: 'organization',
    permissions: ['workforce.people.read'],
    query: listPositionsQuerySchema,
    response: pageSchema(positionSchema),
  },
  {
    operationId: 'createPosition',
    method: 'post',
    path: '/positions',
    summary: 'สร้างตำแหน่ง',
    tag: 'organization',
    permissions: ['workforce.settings.manage'],
    idempotent: true,
    body: createPositionSchema,
    response: positionSchema,
    successStatus: 201,
  },

  // --- people and employment ---
  {
    operationId: 'listPeople',
    method: 'get',
    path: '/people',
    summary: 'รายชื่อบุคคล',
    tag: 'people',
    permissions: ['workforce.people.read'],
    query: listPeopleQuerySchema,
    response: pageSchema(personSchema),
  },
  {
    operationId: 'createPerson',
    method: 'post',
    path: '/people',
    summary: 'สร้างบุคคล',
    tag: 'people',
    permissions: ['workforce.people.manage'],
    idempotent: true,
    body: createPersonSchema,
    response: personSchema,
    successStatus: 201,
  },
  {
    operationId: 'getPerson',
    method: 'get',
    path: '/people/{personId}',
    summary: 'ดูข้อมูลบุคคล',
    tag: 'people',
    permissions: ['workforce.people.read'],
    response: personSchema,
  },
  {
    operationId: 'updatePerson',
    method: 'patch',
    path: '/people/{personId}',
    summary: 'แก้ไขข้อมูลบุคคล',
    tag: 'people',
    permissions: ['workforce.people.manage'],
    body: updatePersonSchema,
    response: personSchema,
  },
  {
    operationId: 'listEmployments',
    method: 'get',
    path: '/employments',
    summary: 'รายการการจ้าง',
    tag: 'people',
    permissions: ['workforce.people.read'],
    query: listEmploymentsQuerySchema,
    response: pageSchema(employmentSchema),
  },
  {
    operationId: 'createEmployment',
    method: 'post',
    path: '/employments',
    summary: 'สร้างการจ้าง',
    tag: 'people',
    permissions: ['workforce.people.manage'],
    idempotent: true,
    body: createEmploymentSchema,
    response: employmentSchema,
    successStatus: 201,
  },
  {
    operationId: 'getEmployment',
    method: 'get',
    path: '/employments/{employmentId}',
    summary: 'ดูการจ้าง',
    tag: 'people',
    permissions: ['workforce.people.read'],
    response: employmentSchema,
  },
  {
    operationId: 'terminateEmployment',
    method: 'post',
    path: '/employments/{employmentId}/terminate',
    summary: 'สิ้นสุดการจ้าง',
    tag: 'people',
    permissions: ['workforce.people.manage'],
    idempotent: true,
    body: terminateEmploymentSchema,
    response: employmentSchema,
  },
  {
    operationId: 'listAssignments',
    method: 'get',
    path: '/employments/{employmentId}/assignments',
    summary: 'ประวัติการสังกัด/ตำแหน่ง (effective-dated)',
    tag: 'people',
    permissions: ['workforce.people.read'],
    response: pageSchema(assignmentSchema),
  },
  {
    operationId: 'createAssignment',
    method: 'post',
    path: '/employments/{employmentId}/assignments',
    summary: 'เพิ่มช่วงการสังกัด/ตำแหน่งใหม่',
    tag: 'people',
    permissions: ['workforce.people.manage'],
    idempotent: true,
    body: createAssignmentSchema,
    response: assignmentSchema,
    successStatus: 201,
  },
  {
    operationId: 'listCompensationRates',
    method: 'get',
    path: '/compensation-rates',
    summary: 'ประวัติฐานค่าจ้าง (effective-dated)',
    tag: 'compensation',
    permissions: ['workforce.payroll.read'],
    query: listCompensationQuerySchema,
    response: pageSchema(compensationSchema),
  },
  {
    operationId: 'createCompensationRate',
    method: 'post',
    path: '/compensation-rates',
    summary: 'บันทึกฐานค่าจ้างช่วงใหม่',
    tag: 'compensation',
    permissions: ['workforce.payroll.prepare'],
    idempotent: true,
    body: createCompensationSchema,
    response: compensationSchema,
    successStatus: 201,
  },

  // --- devices (Phase 2) ---
  {
    operationId: 'listDevices',
    method: 'get',
    path: '/devices',
    summary: 'รายการเครื่องลงเวลา',
    tag: 'devices',
    permissions: ['workforce.devices.read'],
    query: listDevicesQuerySchema,
    response: pageSchema(deviceSchema),
  },
  {
    operationId: 'createDevice',
    method: 'post',
    path: '/devices',
    summary: 'ลงทะเบียนเครื่องใหม่',
    tag: 'devices',
    permissions: ['workforce.devices.manage'],
    idempotent: true,
    body: createDeviceSchema,
    response: deviceSchema,
    successStatus: 201,
  },
  {
    operationId: 'getDevice',
    method: 'get',
    path: '/devices/{deviceId}',
    summary: 'ดูเครื่อง',
    tag: 'devices',
    permissions: ['workforce.devices.read'],
    response: deviceSchema,
  },
  {
    operationId: 'issueDeviceActivationToken',
    method: 'post',
    path: '/devices/{deviceId}/activation-tokens',
    summary: 'ออก activation token ที่ใช้ได้ครั้งเดียว',
    tag: 'devices',
    permissions: ['workforce.devices.manage'],
    idempotent: true,
    body: issueActivationTokenSchema,
    response: activationTokenSchema,
    successStatus: 201,
  },
  {
    operationId: 'revokeDevice',
    method: 'post',
    path: '/devices/{deviceId}/revoke',
    summary: 'เพิกถอนเครื่องและ credential',
    tag: 'devices',
    permissions: ['workforce.devices.revoke'],
    idempotent: true,
    body: revokeDeviceSchema,
    response: deviceSchema,
  },
  {
    operationId: 'listBiometricEnrollments',
    method: 'get',
    path: '/biometric-enrollments',
    summary: 'อ้างอิงการลงทะเบียนลายนิ้วมือ (ไม่มี template)',
    tag: 'devices',
    permissions: ['workforce.devices.read'],
    response: pageSchema(biometricEnrollmentSchema),
  },
  {
    operationId: 'requestBiometricEnrollment',
    method: 'post',
    path: '/biometric-enrollments',
    summary: 'สั่งให้เครื่องลงทะเบียนลายนิ้วมือ',
    tag: 'devices',
    permissions: ['workforce.devices.enroll-biometric'],
    idempotent: true,
    body: requestEnrollmentSchema,
    response: biometricEnrollmentSchema.partial(),
    successStatus: 202,
  },
  {
    operationId: 'deleteBiometricEnrollments',
    method: 'post',
    path: '/employments/{employmentId}/biometric-enrollments:delete',
    summary: 'สั่งลบลายนิ้วมือของพนักงานออกจากทุกเครื่อง',
    tag: 'devices',
    permissions: ['workforce.devices.enroll-biometric'],
    idempotent: true,
    body: deleteEnrollmentSchema,
    response: biometricEnrollmentSchema.partial(),
    successStatus: 202,
  },

  // --- device ingestion (Phase 2) — ลงลายเซ็นด้วยกุญแจของเครื่อง ---
  {
    operationId: 'activateDevice',
    method: 'post',
    path: '/device-activation',
    summary: 'แลก activation token เป็น credential ของเครื่อง',
    tag: 'device-ingestion',
    permissions: null,
    publicReason:
      'เครื่องยังไม่มี credential ที่จะใช้เซ็น; ความปลอดภัยมาจาก token ใช้ครั้งเดียวที่มีวันหมดอายุ',
    body: deviceActivationRequestSchema,
    response: deviceActivationResponseSchema,
  },
  {
    operationId: 'ingestDeviceTimeEvents',
    method: 'post',
    path: '/device-ingestion/time-events:batch',
    summary: 'ส่ง batch เวลาที่บันทึกไว้ (idempotent ตาม sequence)',
    tag: 'device-ingestion',
    permissions: null,
    deviceAuth: true,
    body: deviceBatchSchema,
    response: ingestResultSchema,
    successStatus: 201,
  },
  {
    operationId: 'deviceHeartbeat',
    method: 'post',
    path: '/device-ingestion/heartbeats',
    summary: 'รายงานสถานะเครื่องและ clock drift',
    tag: 'device-ingestion',
    permissions: null,
    deviceAuth: true,
    body: heartbeatSchema,
    response: syncStateSchema.partial(),
    successStatus: 201,
  },
  {
    operationId: 'deviceSyncState',
    method: 'get',
    path: '/device-ingestion/sync-state',
    summary: 'high-water mark ที่ server ยืนยันแล้ว',
    tag: 'device-ingestion',
    permissions: null,
    deviceAuth: true,
    response: syncStateSchema,
  },
  {
    operationId: 'deviceCommands',
    method: 'get',
    path: '/device-ingestion/commands',
    summary: 'คำสั่งที่รอเครื่องทำ',
    tag: 'device-ingestion',
    permissions: null,
    deviceAuth: true,
    response: pageSchema(deviceCommandSchema),
  },
  {
    operationId: 'ackDeviceCommand',
    method: 'post',
    path: '/device-ingestion/commands:ack',
    summary: 'รายงานผลของคำสั่ง (nonce ใช้ได้ครั้งเดียว)',
    tag: 'device-ingestion',
    permissions: null,
    deviceAuth: true,
    body: ackCommandSchema,
    response: syncStateSchema.partial(),
    successStatus: 201,
  },
  {
    operationId: 'legacyAttendance',
    method: 'post',
    path: '/legacy/attendance',
    summary: 'Adapter ชั่วคราวสำหรับ firmware เดิม — ต้องปิดหลัง cutover',
    tag: 'device-ingestion',
    permissions: null,
    publicReason:
      'firmware เดิมเซ็นไม่ได้; ป้องกันด้วย LEGACY_INGEST_KEY และปิดสนิทเมื่อไม่ตั้งค่า',
    body: legacyAttendanceSchema,
    response: syncStateSchema.partial(),
  },

  // --- audit ---
  {
    operationId: 'listAuditEvents',
    method: 'get',
    path: '/audit-events',
    summary: 'ค้นบันทึกการตรวจสอบ',
    tag: 'audit',
    permissions: ['workforce.audit.read'],
    query: listAuditEventsQuerySchema,
    response: pageSchema(auditEventSchema),
  },
];

export function routeKey(method: string, path: string): string {
  return `${method.toUpperCase()} ${API_BASE_PATH}${path}`;
}

export function findRoute(operationId: string): RouteDefinition | undefined {
  return ROUTES.find((route) => route.operationId === operationId);
}
